# -----------------------------------------------------------------------------
# - DOCKERFILE
# - AUTOR: Brian Suarez | Eduardo Franco | Jhon Celemin | Wilman Ortiz
# - FECHA: 06-Octubre-2020
# - DESCRIPCION: Docker-compose que permite la creacion del
# -              contenedor con el servicio de comandos y queries de campanias
# ------------------------------------------------------------------------------

version: '3.7'
services:
  orders-command-services:
    image: wortiz1027/orders-command-services:latest
    container_name: orders-command-services
    hostname: orders-command-services
    restart: always
    ports:
      - 8089:8089
      - 6089:6089
    environment:    
      - CONFIG_SERVER=http://10.39.1.85:9090
      - EUREKA_SERVER=http://10.39.1.85:9091/eureka
      - EUREKA_HOST=10.39.1.85
      - RABBITMQ_HOST=10.39.1.85
      - DB_ORDER_COMMAND_HOST=10.39.1.130      
    networks:
      - ntw_backend
  orders-query-services:
    image: wortiz1027/orders-query-services:latest
    container_name: orders-query-services
    hostname: orders-query-services
    restart: always
    ports:
      - 8090:8090
      - 6090:6090
    environment:    
      - CONFIG_SERVER=http://10.39.1.85:9090
      - EUREKA_SERVER=http://10.39.1.85:9091/eureka
      - EUREKA_HOST=10.39.1.85
      - RABBITMQ_HOST=10.39.1.85
      - DB_ORDER_QUERY_HOST=10.39.1.130      
    networks:
      - ntw_backend
networks:
  ntw_backend:
    external: true